# This is the configuration used to check the rubocop source code.

require:
  - rubocop-performance 
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
  